name: gds
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  gds:
    env:
        OPENLANE_TAG:           2023.02.14
        OPENLANE_IMAGE_NAME:    efabless/openlane:4cd0986b3ae550cdf7a6d0fba4e0657012f635d8-amd64
        OPENLANE_ROOT:          /home/runner/openlane
        PDK_ROOT:               /home/runner/pdk
        PDK:                    sky130A

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          # path depends on the tag and the module name
          name: GDS
          path: |
            src/*
            runs/wokwi/results/final/*

